# Generated by Django 5.0.7 on 2024-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appetizers',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='maindish',
            name='meal',
        ),
        migrations.DeleteModel(
            name='meals',
        ),
    ]
