# Generated by Django 5.0.7 on 2024-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_appetizers_meal_remove_maindish_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appetizers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appetizers/'),
        ),
        migrations.AddField(
            model_name='maindish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/'),
        ),
        migrations.AddField(
            model_name='souces',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='souce/'),
        ),
    ]
